zpdldhy/DD44

Engine/Engine.vcxproj, Engine/Engine.vcxproj.filters, Engine/Inputlayout.cpp, Engine/Inputlayout.h, Engine/UMaterial.cpp, Engine/UMaterial.h
Shader, Texture, Inputlayout을 멤버로 가지는 Material Class 생성 경로를 받아 Shader, Texture를 가져오는 Load 함수 구현
필요할 때 Texture, Shader를 바꿀 수 있는 Set함수 구현
Mesh에서 Texture, Shader, Inputlayout을 가져올 수 있도록 Get함수 구현
=> Feat : "Material Class 추가"

Engine/Define.h, Engine/Engine.cpp, Engine/Timer.cpp, Engine/Timer.h
=> Feat : "FPS 화면에 출력"

Engine/DxWrite.cpp, Engine/DxWrite.h, Engine/Engine.cpp, Engine/ShaderStructs.cpp, Engine/ShaderStructs.h, Game/.hlsli, Game/TestSJ.cpp
=> Feat: 'Draw Grow'추가

Engine/Define.h, Engine/Engine.cpp, Engine/Engine.vcxproj, Engine/Engine.vcxproj.filters, Engine/Functions.h, Engine/Sound.cpp, Engine/Sound.h, Game/Game.vcxproj, Game/Main.cpp, Game/TestSJ.cpp, Game/TestSJ.h
Function에 to_mw, to_wm 추가
ImGui Destroy추가
Sound 2D 추가
Material 매개변수_ 추가
TestSJ Test
=> Feat:"Add Sound"

Engine/ASky.cpp, Engine/DxState.cpp, Engine/DxState.h, Engine/EffectEditorUI.cpp, Engine/EffectEditorUI.h, Engine/ImGuiCore.cpp, Engine/ImGuiCore.h, Engine/UMaterial.cpp, Engine/UMaterial.h, Game/Game.vcxproj, Game/Game.vcxproj.filters, Game/Main.cpp, Game/TestSJ.cpp, Game/TestSJ.h, Game/imgui.ini, Resources/Shader/Header.hlsli
imgui EffectEditorUI 변경
shader 파일정리
stencil효과 추가
skybox 메모리 릭 정리
=> Feat/add effect editor UI

Engine/Engine.cpp, Engine/Texture.h, Engine/ViewPortTexture.cpp, Engine/ViewPortTexture.h
UMaterial::SetTexture를 통해 해당 class를 넣어 사용할 수 있도록 변경
=> Feat : "ViewPortTexture를 Texture를 상속받도록 변경"

Engine/AUIActor.cpp, Engine/AUIActor.h, Engine/Define.h, Engine/Engine.cpp, Engine/Engine.h, Engine/Engine.vcxproj, Engine/Engine.vcxproj.filters, Engine/Texture.cpp, Engine/Texture.h, Engine/UCameraComponent.cpp, Engine/UCameraComponent.h, Engine/UIManager.cpp, Engine/UIManager.h, Game/Main.cpp, Game/TestSY.cpp, Game/TestSY.h
UI를 모아서 Render하는 UIManager 구현
UIManager에서는 AUIActor만 List로 받아 Render하도록 구현
=> Feat : "UI Manager 구현"

Engine/EffectEditorUI.cpp, Engine/ImGuiCore.h, Game/TestSJ.cpp, Game/imgui.ini
=> Refactor/effectUI callback 함수이동

Game/Main.cpp, Game/TestSY.cpp, Game/TestSY.h
Init을 하고 AddActor를 하면 생기는 현상을 해결
매 Frame마다 UIList를 emplace_back하며 생기는 현상 해결
=> Fix : "TestTS에서의 RefCount 문제 해결"

Engine/ActorLoader.cpp, Engine/ActorLoader.h, Engine/FbxLoader.cpp, Engine/FbxLoader.h, Engine/UAnimInstance.cpp, Engine/UAnimInstance.h, Engine/UStaticMeshComponent.cpp, Engine/UStaticMeshComponent.h, Game/Main.cpp, Game/PlayerMoveScript.cpp, Game/TestPlayer.cpp, Game/TestPlayer.h, Game/TestYR.cpp, Game/TestYR.h, Resources/Shader/skinningShader.hlsl
자식 관계 없는 mesh로 리턴.
childMesh의 위치 변경으로 눈, 검 붙이기.
=> Feat : "ActorLoader 의 LoadMesh 수정"

Engine/CameraManager.cpp, Engine/CameraManager.h, Engine/EffectEditorUI.cpp, Engine/EffectEditorUI.h, Engine/ImGuiCore.h, Engine/PostProcessManager.cpp, Engine/ULightComponent.cpp, Engine/UMaterial.cpp, Engine/UMaterial.h, Game/Main.cpp, Game/TestSJ.cpp, Resources/Shader/Header.hlsli, Resources/Shader/PREffect.hlsl
=> Refactor/CB정리 및 material 자체 빛생성

Engine/UCameraComponent.cpp, Game/Game.cpp, Game/Game.h
O키를 눌러 Engine Camera 와 GameCamera 변경
=> Feat : "Engine Camera 추가"

Engine/UTerrainMeshComponent.cpp, Engine/UTerrainMeshComponent.h
=> Fix : "TerrainMeshComponent에 Transform 미적용 수정"

Game/Editor.cpp, Game/Editor.h, Game/Game.cpp, Game/Game.h, Game/Game.vcxproj, Game/Game.vcxproj.filters, Game/GameCameraMove.cpp, Game/GameCameraMove.h, Game/Main.cpp, Game/PlayerMoveScript.cpp, Game/PlayerMoveScript.h
GameCamera를 씬에서 생성 및 설정.
offset 값은 하드코딩으로 넣음. offset 유지하며 위치만 변경.
GameCamera 적용을 위한 Editor/Game 씬 변경, MyCharacter.chracter.json 수정. Editor에서 Slash 와 Blood 제거.
=> Feat : "GameCamera 생성 및 Editor / Game 씬 변경"

Game/BatMovement.cpp, Game/BatMovement.h
=> Fix : "rotate speed 변수 변경"

Engine/AActor.cpp, Engine/CollisionManager.cpp, Engine/Engine.cpp, Engine/UAnimInstance.cpp, Engine/UAnimInstance.h, Engine/UShapeComponent.h, Game/BatMovement.cpp, Game/BatMovement.h, Game/Editor.cpp, Game/Editor.h, Game/Game.cpp, Game/Game.h, Game/Game.vcxproj, Game/Game.vcxproj.filters, Game/PlayerMoveScript.cpp, Game/PlayerMoveScript.h, Game/PlayerStates.cpp, Game/PlayerStates.h, Game/PrefabToActor.cpp, Game/TestYR.cpp, Game/TestYR.h, Game/WalkerMovement.cpp, Game/WalkerMovement.h, Game/WalkerStates.cpp, Game/WalkerStates.h, Game/imgui.ini
- 임시 충돌 및 거리 확인을 통한 플레이어-몬스터 상호작용
- bat과 walker(머리없는구울) fsm 추가
- 코드 리펙토링 필수 .. 캐릭터 스크립트 기능별 분리 필요
=> Feat/Interaction With Enemy

Game/BettyMovement.cpp, Game/BettyMovement.h, Game/BettyStates.cpp, Game/BettyStates.h, Game/PlayerMoveScript.cpp
- betty 플레이어 거리 확인해서 쿵 모션 실행
- player 죽었을 때 L키 누르면 살아나도록.
=> Feat : "betty와 player 업데이트"

Game/BatMovement.cpp, Game/TCharacter.cpp, Game/TCharacter.h, Game/TEnemy.cpp, Game/TEnemy.h
=> Feat:"Enemy Crack 추가"

Game/PlayerStates.cpp
=> fix : "attack 끝날떄 슬래쉬 무조건 render false"

Engine/EffectManager.cpp, Engine/EffectManager.h
초기에 최소개수만 생성
추가로 사용시 생성해서 pool로 관리
시작시 effect한번 터트려서 처음 시작해도 생성됨.
=> Refacotr:"EffectPool"구조 변경

Game/Game.vcxproj, Game/Game.vcxproj.filters, Resources/Shader/skinningShaderNoLight.hlsl
=> Chore : "빛 안받는 skinningMesh 용 쉐이더 생성"

Engine/CameraManager.cpp, Engine/CameraManager.h, Engine/CollisionManager.cpp, Engine/CollisionManager.h, Game/Game.cpp, Game/Game.h, Game/TEnemy.cpp, Game/TEnemy.h
Frustum 내부 Enemy만 CheckCollision하도록 수정
=> Feat : "Enemy 와 Frustum 평면 충돌"

Engine/Engine.cpp, Game/EventManager.cpp, Game/EventManager.h, Game/FenceScript.cpp, Game/Game.cpp, Game/Game.h, Game/StageManager.cpp, Game/StageManager.h
=> feat : "입장 트리거 생성"
